name: Docker Image CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - entrypoint.sh
      - haproxy/**

jobs:
  BuildEggHAProxy:
    runs-on: ubuntu-latest

    steps:
      - name: Checking Repostiory
        uses: actions/checkout@v3

      - name: Setup multiarch
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build & Push EggHAProxy Image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/numa-lab/docker-haproxy:latest
